import type Piece from '../Piece';
import type Position from '../Position';
import { type Rank, type File } from '../Position';
import type Resolution from '../Resolution';
import type Board from './Board';
declare const hasN: (pos: Position, distance?: 1 | 2) => boolean;
declare const hasS: (pos: Position, distance?: 1 | 2) => boolean;
declare const hasE: (pos: Position, distance?: 1 | 2) => boolean;
declare const hasW: (pos: Position, distance?: 1 | 2) => boolean;
declare const getNRank: (pos: Position, distance?: 1 | 2) => Rank;
declare const getSRank: (pos: Position, distance?: 1 | 2) => Rank;
declare const getEFile: (pos: Position, distance?: 1 | 2) => File;
declare const getWFile: (pos: Position, distance?: 1 | 2) => File;
declare const nextNE: (pos: Position) => Position | null;
declare const nextSE: (pos: Position) => Position | null;
declare const nextNW: (pos: Position) => Position | null;
declare const nextSW: (pos: Position) => Position | null;
declare const nextN: (pos: Position) => Position | null;
declare const nextS: (pos: Position) => Position | null;
declare const nextE: (pos: Position) => Position | null;
declare const nextW: (pos: Position) => Position | null;
declare const resolvableMovesAndCapture: (board: Board, piece: Piece, from: Position, getNext: (pos: Position) => Position | null) => Resolution[];
export { hasN, hasS, hasE, hasW, getNRank, getSRank, getEFile, getWFile, nextN, nextS, nextE, nextW, nextNE, nextNW, nextSE, nextSW, resolvableMovesAndCapture, };
